FROM node:18

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Expose React port
EXPOSE 3000

# Start React app
CMD ["npm", "start"]
